config/routes.rb
Rails.application.routes.draw do
  mount LoldesignPublisher::Rails::Engine => '/'

  root "home#index"
  
  resources :products, path: 'produtos', except: :destroy do
    collection do 
      resources :available_products, only: :destroy
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_product.rb
# == Schema Information
#
# Table name: available_products
#
#  id         :integer          not null, primary key
#  product_id :integer
#  color_id   :integer
#  size_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class AvailableProduct < ApplicationRecord
  belongs_to :product
  belongs_to :color
  belongs_to :size

  validates :quantity,
            :size_id,
            :color_id, presence: true
end

app/models/color.rb
# == Schema Information
#
# Table name: colors
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Color < ApplicationRecord
  has_many :available_products

  validates :name, presence: true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Product < ApplicationRecord
  has_many :available_products, dependent: :destroy
  validates :name,
            :description,
            presence: true

  accepts_nested_attributes_for :available_products, allow_destroy: true
end

app/models/size.rb
# == Schema Information
#
# Table name: sizes
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Size < ApplicationRecord
  has_many :available_products

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/available_products_controller.rb
class AvailableProductsController < LoldesignPublisher::PublisherController
  def destroy
    available_product = AvailableProduct.where(id: params[:id])

    if available_product.present? && available_product.first.destroy
      redirect_to products_path, notice: 'Produto removido com sucesso!', status: 202
    else
      redirect_to products_path, notice: 'Não foi possível remover o produto, tente novamente.', status: 422
    end
  end
end

app/controllers/home_controller.rb
class HomeController < LoldesignPublisher::PublisherController
  protect_from_forgery with: :exception

  def index
    
  end
  
end

app/controllers/products_controller.rb
class ProductsController < LoldesignPublisher::PublisherController
  before_action :load_product, except: [:index, :new, :create]

  def index
    @available_products = AvailableProduct.order('created_at DESC')
                                          .page(params[:page] || 1)
                                          .per_page(30)
  end

  def new
    @product = Product.new()
    @product.available_products.build()
  end

  def create
    @product = Product.new(products_params)

    if @product.save
      redirect_to products_path, notice: 'Produtos cadastrados com sucesso!', status: 202
    else
      render action: :new, alert: 'Não foi possível cadastrar os produtos, tente novamente.', status: 422
    end
  end

  def edit
    @product.available_products.build()
  end

  def update
    if @product.update_attributes(products_params)
      redirect_to products_path, notice: 'Produtos atualizados com sucesso!', status: 202
    else
      render action: :edit, alert: 'Não foi possível atualizadar os produtos, tente novamente.', status: 422
    end
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def products_params
    params
      .require(:product)
      .permit(
        :name,
        :description,
        available_products_attributes: [
          :id, 
          :color_id, 
          :size_id, 
          :quantity, 
          :_destroy
        ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/available_products/_available_product.html.erb
<tr>
  <td><%= available_product.product.name %></td>
  <td><%= available_product.product.description %></td>
  <td><%= available_product.color.id %></td>
  <td><%= available_product.size.name %></td>
  <td><%= available_product.quantity %></td>
  <td>
    <%= edit_resource edit_product_path(available_product.product) %>
    <%= remove_resource available_product_path(available_product), {}%>
  </td>
</tr>

app/views/home/index.html.erb
<%= title_page 'Bem vindo!' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Synergia Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/loldesign_publisher/publisher.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Rails</title>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <%= stylesheet_link_tag 'loldesign_publisher/publisher', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: '/layouts/loldesign_publisher/header_main' %>

  <section class='container'>
    <%= render partial: '/layouts/loldesign_publisher/nav_main' %>
    <section class='content-wrapper'>

      <%= render partial: '/layouts/loldesign_publisher/modules/messages' %>

      <%= yield %>
    </section>
  </section>
  <%= javascript_include_tag 'loldesign_publisher/publisher' %>
  <%= javascript_include_tag '/grid.js' if Rails.env.development? %>
</body>
</html>

app/views/products/_form.html.erb
<%= simple_nested_form_for @product, html: { id: 'product--form', multipart: true } do |f| %>

  <section class='fields-wrapper one-column'>
    <header>
      <h2>Destaque</h2>
    </header>
    <article>
      <%= f.input :name, wrapper_html: {class: 'col-18'} %>
      <%= f.input :description, wrapper_html: {class: 'col-18'} %>

      <%= f.fields_for :available_products, wrapper_html: { class: 'col-18' } do |ff| %>
          <div class="col-5">
            <%= ff.label  :color_id, class: 'col-18' %>
            <%= ff.select :color_id, options_for_select(Color.all.collect{ |color| [color.name, color.id] }, ff.object.color_id), include_blank: true %>
          </div>
          <div class="col-5">
            <%= ff.label  :size_id, class: 'col-18' %>
            <%= ff.select :size_id, options_for_select(Size.all.collect{ |size| [size.name, size.id] }, ff.object.size_id), include_blank: true %>
          </div>
          <div class="col-5">
            <%= ff.input :quantity, as: :integer %>
          </div>
          <div class="col-2">
            <%= ff.link_to_remove "Remover" %>
          </div>
      <% end %>
      <br>
      <%= f.link_to_add "Adicionar", :available_products, class: 'col-3' %>
    </article>
  </section>

  <footer>
    <%= cancel_action(path: products_path) %>
    <%= submit_button f %>
  </footer>
<% end %>

app/views/products/edit.html.erb
<%= title_page "Editar" %>

<%= render 'form'  %>

app/views/products/index.html.erb
<%= add_resource 'Novo Produto', new_product_path %>
<%= title_page "Produtos disponíveis" %>

<table class='table-page'>
  <thead>
    <tr>
      <th><%= Product.human_attribute_name(:name) %></th>
      <th><%= Product.human_attribute_name(:description) %></th>
      <th><%= AvailableProduct.human_attribute_name(:color) %></th>
      <th><%= AvailableProduct.human_attribute_name(:size) %></th>
      <th><%= AvailableProduct.human_attribute_name(:quantity) %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <%= display_list_for(@available_products, fields: 6) %>
  </tbody>
</table>

<%= will_paginate @available_products %>

app/views/products/new.html.erb
<%= title_page "Novo" %>

<%= render 'form'  %>